import { Component, inject, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Api } from './api.service';
import { I18n } from './i18n.service';
import { User, Role } from './models';
import { MATERIAL } from './material';
type Resource='users'|'categories'|'areas'|'technicians';
interface Entry {id:number;name:string;email?:string;role?:Role;description?:string;userId?:number;specialty?:string;active:boolean;}
interface Editor {name:string;email:string;password:string;role:Role;description:string;userId:number|null;specialty:string;active:boolean;}
@Component({standalone:true,imports:[FormsModule,...MATERIAL],template:`
<div class="page-heading"><div><h1>{{i.t('Administración','Administration')}}</h1><p>{{i.t('Gestiona las personas y los recursos de la plataforma.','Manage the people and resources on the platform.')}}</p></div></div>
<nav class="resource-tabs" [attr.aria-label]="i.t('Recursos administrables','Manageable resources')">@for(tab of tabs;track tab.key){<button mat-button [class.selected]="resource===tab.key" (click)="select(tab.key)">{{i.t(tab.es,tab.en)}}</button>}</nav>
@if(error){<p role="alert" class="alert error">{{error}}</p>}@if(message){<p role="status" class="alert success">{{message}}</p>}@if(loading){<mat-progress-bar mode="indeterminate" [attr.aria-label]="i.t('Cargando recursos','Loading resources')"/>}
<div class="admin-layout"><section class="panel"><div class="section-heading"><h2>{{resourceTitle()}}</h2><button mat-stroked-button (click)="reset()">＋ {{i.t('Nuevo','New')}}</button></div><div class="table-scroll"><table><caption class="sr-only">{{resourceTitle()}}</caption><thead><tr><th>{{i.t('Nombre','Name')}}</th><th>{{i.t('Detalle','Details')}}</th><th>{{i.t('Estado','Status')}}</th><th>{{i.t('Acciones','Actions')}}</th></tr></thead><tbody>@for(row of rows;track row.id){<tr><td>{{row.name}}</td><td>{{row.email || row.description || row.specialty}}@if(row.role){<small>{{i.label(row.role)}}</small>}</td><td>{{row.active?i.t('Activo','Active'):i.t('Inactivo','Inactive')}}</td><td><button mat-button (click)="edit(row)">{{i.t('Editar','Edit')}}</button>@if(row.active){<button mat-button class="danger" (click)="deleting=row">{{i.t('Desactivar','Deactivate')}}</button>}</td></tr>}</tbody></table></div>@if(!rows.length&&!loading){<p class="empty-state">{{i.t('No hay registros. Crea el primero.','No records. Create the first one.')}}</p>}
@if(deleting;as row){<div class="alert error"><p>{{i.t('Se desactivará','This will deactivate')}} {{row.name}}. {{i.t('Se conservará su historial.','History will be preserved.')}}</p><button mat-button (click)="deleting=null">{{i.t('Cancelar','Cancel')}}</button><button mat-flat-button (click)="deactivate(row)" [disabled]="busy">{{i.t('Confirmar','Confirm')}}</button></div>}</section>
<form class="panel" #form="ngForm" (ngSubmit)="save()"><h2>{{editingId?i.t('Editar registro','Edit record'):i.t('Crear registro','Create record')}}</h2>
@if(resource!=='technicians'){<mat-form-field appearance="outline"><mat-label>{{i.t('Nombre','Name')}}</mat-label><input matInput name="name" [(ngModel)]="editor.name" required maxlength="150"><mat-error>{{i.t('El nombre es obligatorio.','Name is required.')}}</mat-error></mat-form-field>}
@if(resource==='users'){<mat-form-field appearance="outline"><mat-label>{{i.t('Correo electrónico','Email address')}}</mat-label><input matInput type="email" name="email" [(ngModel)]="editor.email" required email maxlength="200"><mat-error>{{i.t('Ingresa un correo válido.','Enter a valid email.')}}</mat-error></mat-form-field><mat-form-field appearance="outline"><mat-label>{{editingId?i.t('Nueva contraseña (opcional)','New password (optional)'):i.t('Contraseña','Password')}}</mat-label><input matInput type="password" name="password" [(ngModel)]="editor.password" [required]="!editingId" minlength="10" maxlength="72" autocomplete="new-password"><mat-error>{{i.t('Usa entre 10 y 72 caracteres.','Use between 10 and 72 characters.')}}</mat-error></mat-form-field><mat-form-field appearance="outline"><mat-label>{{i.t('Rol','Role')}}</mat-label><mat-select name="role" [(ngModel)]="editor.role" required>@for(role of roles;track role){<mat-option [value]="role">{{i.label(role)}}</mat-option>}</mat-select></mat-form-field>}
@if(resource==='categories'||resource==='areas'){<mat-form-field appearance="outline"><mat-label>{{i.t('Descripción','Description')}}</mat-label><textarea matInput name="description" [(ngModel)]="editor.description" maxlength="500"></textarea></mat-form-field>}
@if(resource==='technicians'){<mat-form-field appearance="outline"><mat-label>{{i.t('Usuario técnico','Technician user')}}</mat-label><mat-select name="userId" [(ngModel)]="editor.userId" required>@for(user of techUsers;track user.id){<mat-option [value]="user.id">{{user.name}} · {{user.email}}</mat-option>}</mat-select><mat-error>{{i.t('Selecciona un usuario técnico.','Select a technician user.')}}</mat-error></mat-form-field><p class="muted">{{i.t('Primero crea un usuario con rol Técnico en Usuarios.','First create a user with the Technician role in Users.')}}</p><mat-form-field appearance="outline"><mat-label>{{i.t('Especialidad','Specialty')}}</mat-label><input matInput name="specialty" [(ngModel)]="editor.specialty" required maxlength="150"></mat-form-field>}
<mat-checkbox name="active" [(ngModel)]="editor.active">{{i.t('Activo','Active')}}</mat-checkbox><div class="form-actions"><button mat-button type="button" (click)="reset()">{{i.t('Limpiar','Reset')}}</button><button mat-flat-button type="submit" [disabled]="form.invalid||busy">{{busy?i.t('Guardando…','Saving…'):i.t('Guardar','Save')}}</button></div></form></div>`})
export class AdminComponent implements OnInit {
  api=inject(Api);i=inject(I18n);resource:Resource='users';rows:Entry[]=[];techUsers:User[]=[];editingId:number|null=null;deleting:Entry|null=null;loading=false;busy=false;error='';message='';roles=['REPORTER','TECHNICIAN','ADMIN'];tabs:{key:Resource;es:string;en:string}[]=[{key:'users',es:'Usuarios',en:'Users'},{key:'categories',es:'Categorías',en:'Categories'},{key:'areas',es:'Áreas',en:'Areas'},{key:'technicians',es:'Técnicos',en:'Technicians'}];editor=this.blank();
  blank():Editor{return{name:'',email:'',password:'',role:'REPORTER',description:'',userId:null,specialty:'',active:true};}ngOnInit(){void this.load();}resourceTitle(){const t=this.tabs.find(t=>t.key===this.resource)!;return this.i.t(t.es,t.en);}reset(){this.editor=this.blank();this.editingId=null;this.deleting=null;}async select(resource:Resource){this.resource=resource;this.reset();this.message='';await this.load();}
  async load(){this.loading=true;this.error='';try{this.rows=await this.api.get<Entry[]>('/'+this.resource);if(this.resource==='technicians')this.techUsers=(await this.api.get<User[]>('/users')).filter(u=>u.role==='TECHNICIAN'&&u.active);}catch(e){this.error=this.api.error(e);}finally{this.loading=false;}}
  edit(row:Entry){this.editingId=row.id;this.editor={...this.blank(),...row,password:''};this.message='';}
  async save(){this.busy=true;this.error='';const e=this.editor;const payload=this.resource==='users'?{name:e.name,email:e.email,role:e.role,active:e.active,...(e.password?{password:e.password}:{})}:this.resource==='technicians'?{userId:e.userId,specialty:e.specialty,active:e.active}:{name:e.name,description:e.description,active:e.active};try{await this.api.write(this.editingId?'PUT':'POST','/'+this.resource+(this.editingId?'/'+this.editingId:''),payload);this.reset();await this.load();this.message=this.i.t('Registro guardado.','Record saved.');}catch(err){this.error=this.api.error(err);}finally{this.busy=false;}}
  async deactivate(row:Entry){this.busy=true;try{await this.api.write('DELETE','/'+this.resource+'/'+row.id);this.deleting=null;await this.load();this.message=this.i.t('Registro desactivado.','Record deactivated.');}catch(e){this.error=this.api.error(e);}finally{this.busy=false;}}
}
