import { Component, inject, OnInit } from '@angular/core';
import { RouterLink } from '@angular/router';
import { Api } from './api.service';
import { I18n } from './i18n.service';
import { Dashboard, Metric } from './models';
import { MATERIAL } from './material';
@Component({standalone:true,imports:[RouterLink,...MATERIAL],template:`
<div class="page-heading"><div><h1>{{i.t('Vista general','Overview')}}</h1><p>{{i.t('Todo lo que necesitas para dar el siguiente paso.','Everything you need to take the next step.')}}</p></div>@if(api.user()?.role !== 'TECHNICIAN'){<a mat-flat-button routerLink="/reports/new">＋ {{i.t('Nueva incidencia','New report')}}</a>}</div>
@if(loading){<mat-progress-bar mode="indeterminate" [attr.aria-label]="i.t('Cargando indicadores','Loading metrics')"/>}
@if(error){<div class="alert error" role="alert">{{error}} <button mat-button (click)="load()">{{i.t('Reintentar','Retry')}}</button></div>}
@if(data; as d){
<div class="metric-grid"><article class="metric"><span>{{i.t('Incidencias registradas','Total reports')}}</span><strong>{{d.total}}</strong><small>{{i.t('Según tu acceso','Based on your access')}}</small></article><article class="metric"><span>{{i.t('Pendientes de atención','Open reports')}}</span><strong>{{d.open}}</strong><small>{{i.t('Nuevas, asignadas o en atención','New, assigned or in progress')}}</small></article><article class="metric"><span>{{i.t('Resueltas','Resolved')}}</span><strong>{{d.resolved}}</strong><small>{{i.t('Esperando confirmación de cierre','Awaiting closure confirmation')}}</small></article><article class="metric"><span>{{i.t('Cerradas','Closed')}}</span><strong>{{d.closed}}</strong><small>{{i.t('Ciclo completado','Cycle completed')}}</small></article></div>
<div class="dashboard-grid"><section class="panel"><div class="section-heading"><h2>{{i.t('Estado de las incidencias','Report status')}}</h2><a routerLink="/reports">{{i.t('Ver incidencias','View reports')}} →</a></div>@if(!d.total){<div class="empty-state"><span aria-hidden="true">✓</span><h3>{{i.t('Todavía no hay incidencias','No reports yet')}}</h3><p>{{i.t('Los indicadores aparecerán al registrar el primer reporte.','Metrics will appear after the first report.')}}</p></div>}@for(item of d.byStatus;track item.label){<div class="bar-row"><span>{{i.label(item.label)}}</span><div class="bar-track"><div [style.width.%]="percent(item.count,d.total)"></div></div><strong>{{item.count}}</strong></div>}</section><section class="panel accent-panel"><h2>{{i.t('Una comunidad que actúa.','A community that takes action.')}}</h2><p>{{i.t('Describe el problema con claridad. El equipo responsable podrá atenderlo y mantenerte al tanto.','Describe the problem clearly. The responsible team can address it and keep you informed.')}}</p><div class="resolution"><strong>{{d.averageResolutionHours === null ? '—' : d.averageResolutionHours.toFixed(1) + ' h'}}</strong><span>{{i.t('Promedio hasta resolución','Average time to resolution')}}</span></div></section></div>
<div class="two-columns">@for(group of groups(d);track group.title){<section class="panel"><h2>{{group.title}}</h2>@if(!group.items.length){<p class="muted">{{i.t('Sin datos disponibles.','No data available.')}}</p>}@for(item of group.items;track item.label){<div class="stat-row"><span>{{item.label}}</span><strong>{{item.count}}</strong></div>}</section>}</div>
<section class="panel month-panel"><h2>{{i.t('Registros por mes (UTC)','Reports by month (UTC)')}}</h2><div class="months">@for(item of d.byMonth;track item.label){<div><strong>{{item.count}}</strong><span>{{item.label}}</span></div>}@empty {<p class="muted">{{i.t('Aún no hay actividad.','No activity yet.')}}</p>}</div></section>
}`})
export class DashboardComponent implements OnInit {api=inject(Api);i=inject(I18n);data:Dashboard|null=null;loading=false;error='';ngOnInit(){void this.load();}async load(){this.loading=true;this.error='';try{this.data=await this.api.get<Dashboard>('/dashboard');}catch(e){this.error=this.api.error(e);}finally{this.loading=false;}}percent(count:number,total:number){return total?count/total*100:0;}groups(d:Dashboard):{title:string;items:Metric[]}[]{return[{title:this.i.t('Por categoría','By category'),items:d.byCategory},{title:this.i.t('Por área','By area'),items:d.byArea}];}}
