import { Component, inject, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { Api } from './api.service';
import { I18n } from './i18n.service';
import { Catalog, Report, ReportDraft, Suggestion } from './models';
import { MATERIAL } from './material';
@Component({standalone:true,imports:[FormsModule,RouterLink,...MATERIAL],template:`
<a routerLink="/reports" class="back-link">← {{i.t('Volver a incidencias','Back to reports')}}</a><div class="page-heading"><div><h1>{{id ? i.t('Editar incidencia','Edit report') : i.t('Nueva incidencia','New report')}}</h1><p>{{i.t('Cuéntanos qué ocurre y dónde podemos encontrarlo.','Tell us what happened and where to find it.')}}</p></div></div>
@if(loading){<mat-progress-bar mode="indeterminate" [attr.aria-label]="i.t('Cargando formulario','Loading form')"/>}
@if(error){<p class="alert error" role="alert">{{error}}</p>}
@if(!loading && ready){<div class="form-layout"><form class="panel" #form="ngForm" (ngSubmit)="save()"><h2>{{i.t('Detalles del problema','Issue details')}}</h2><mat-form-field appearance="outline"><mat-label>{{i.t('Descripción','Description')}}</mat-label><textarea matInput name="description" [(ngModel)]="draft.description" rows="5" required minlength="10" maxlength="4000"></textarea><mat-hint>{{i.t('Qué observaste, desde cuándo y cómo afecta el uso del espacio.','What you noticed, since when, and how it affects the space.')}}</mat-hint><mat-error>{{i.t('Escribe entre 10 y 4000 caracteres.','Use between 10 and 4000 characters.')}}</mat-error></mat-form-field>
<button mat-stroked-button type="button" (click)="suggest()" [disabled]="aiBusy || draft.description.length<10">✧ {{aiBusy ? i.t('Consultando…','Requesting…') : i.t('Ayudarme con IA','Help me with AI')}}</button>
@if(suggestion;as s){<div class="suggestion" aria-live="polite"><strong>{{i.label(s.source)}}</strong><p>{{s.explanation}}</p>@if(s.source==='AI'){<p>{{s.title}}</p><p>{{s.summary}}</p><p>{{s.priority ? i.label(s.priority) : ''}}</p><button mat-button type="button" (click)="applySuggestion()">{{i.t('Usar sugerencia y revisar','Use suggestion and review')}}</button>}@else{<p>{{i.t('Continúa completando los campos manualmente.','Continue filling out the fields manually.')}}</p>}</div>}
<mat-form-field appearance="outline"><mat-label>{{i.t('Título','Title')}}</mat-label><input matInput name="title" [(ngModel)]="draft.title" required minlength="5" maxlength="150"><mat-error>{{i.t('Escribe entre 5 y 150 caracteres.','Use between 5 and 150 characters.')}}</mat-error></mat-form-field>
<div class="two-columns"><mat-form-field appearance="outline"><mat-label>{{i.t('Categoría','Category')}}</mat-label><mat-select name="categoryId" [(ngModel)]="draft.categoryId" required>@for(c of categories;track c.id){<mat-option [value]="c.id">{{c.name}}</mat-option>}</mat-select><mat-error>{{i.t('Selecciona una categoría.','Select a category.')}}</mat-error></mat-form-field><mat-form-field appearance="outline"><mat-label>{{i.t('Área del campus','Campus area')}}</mat-label><mat-select name="areaId" [(ngModel)]="draft.areaId" required>@for(a of areas;track a.id){<mat-option [value]="a.id">{{a.name}}</mat-option>}</mat-select><mat-error>{{i.t('Selecciona un área.','Select an area.')}}</mat-error></mat-form-field></div>
<mat-form-field appearance="outline"><mat-label>{{i.t('Ubicación exacta','Exact location')}}</mat-label><input matInput name="location" [(ngModel)]="draft.location" required maxlength="250"><mat-hint>{{i.t('Ej.: Pabellón A, piso 2, junto a las escaleras.','E.g. Building A, floor 2, next to the stairs.')}}</mat-hint><mat-error>{{i.t('Indica la ubicación.','Enter the location.')}}</mat-error></mat-form-field><mat-form-field appearance="outline"><mat-label>{{i.t('Prioridad','Priority')}}</mat-label><mat-select name="priority" [(ngModel)]="draft.priority" required>@for(p of priorities;track p){<mat-option [value]="p">{{i.label(p)}}</mat-option>}</mat-select></mat-form-field>
<div class="form-actions"><a mat-button routerLink="/reports">{{i.t('Cancelar','Cancel')}}</a><button mat-flat-button type="submit" [disabled]="form.invalid||busy">{{busy ? i.t('Guardando…','Saving…') : i.t('Guardar incidencia','Save report')}}</button></div></form><aside class="panel tips"><h2>{{i.t('Pequeños detalles. Mejores soluciones.','Small details. Better solutions.')}}</h2><p>{{i.t('Describe hechos concretos y evita incluir datos personales de otras personas.','Describe specific facts and avoid including other people’s personal information.')}}</p><hr><h3>{{i.t('Tú tienes la última palabra','You have the final say')}}</h3><p>{{i.t('La IA solo sugiere. Revisa el título, la categoría y la prioridad antes de guardar. Si el proveedor no está disponible, el registro manual sigue funcionando.','AI only suggests. Review the title, category and priority before saving. If the provider is unavailable, manual entry remains available.')}}</p><hr><p>{{i.t('Para emergencias, utiliza los canales de seguridad de tu campus.','For emergencies, use your campus security channels.')}}</p></aside></div>}`})
export class ReportFormComponent implements OnInit {api=inject(Api);i=inject(I18n);route=inject(ActivatedRoute);router=inject(Router);id=Number(this.route.snapshot.paramMap.get('id'))||null;draft:ReportDraft={title:'',description:'',location:'',categoryId:null,areaId:null,priority:'MEDIUM'};categories:Catalog[]=[];areas:Catalog[]=[];priorities=['LOW','MEDIUM','HIGH','CRITICAL'];suggestion:Suggestion|null=null;loading=true;ready=false;busy=false;aiBusy=false;error='';async ngOnInit(){try{[this.categories,this.areas]=await Promise.all([this.api.get<Catalog[]>('/categories'),this.api.get<Catalog[]>('/areas')]);this.categories=this.categories.filter(c=>c.active);this.areas=this.areas.filter(a=>a.active);if(this.id){const r=await this.api.get<Report>('/reports/'+this.id);this.draft={title:r.title,description:r.description,location:r.location,categoryId:r.categoryId,areaId:r.areaId,priority:r.priority};}this.ready=true;}catch(e){this.error=this.api.error(e);}finally{this.loading=false;}}async suggest(){this.aiBusy=true;this.error='';try{this.suggestion=await this.api.write<Suggestion>('POST','/ai/suggest',{description:this.draft.description});}catch(e){this.error=this.api.error(e);}finally{this.aiBusy=false;}}applySuggestion(){const s=this.suggestion;if(!s||s.source!=='AI')return;if(s.title)this.draft.title=s.title;if(s.summary)this.draft.description=s.summary;if(s.priority)this.draft.priority=s.priority;if(s.categoryId&&this.categories.some(c=>c.id===s.categoryId))this.draft.categoryId=s.categoryId;this.suggestion=null;}async save(){this.busy=true;this.error='';try{const r=await this.api.write<Report>(this.id?'PUT':'POST','/reports'+(this.id?'/'+this.id:''),this.draft);await this.router.navigate(['/reports',r.id]);}catch(e){this.error=this.api.error(e);}finally{this.busy=false;}}}
