import { Component, inject, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { Api } from './api.service';
import { I18n } from './i18n.service';
import { Catalog, Report } from './models';
import { MATERIAL } from './material';
@Component({standalone:true,imports:[FormsModule,RouterLink,...MATERIAL],template:`
<div class="page-heading"><div><h1>{{i.t('Incidencias','Reports')}}</h1><p>{{i.t('Consulta los reportes a los que tienes acceso.','View reports available to your role.')}}</p></div>@if(api.user()?.role!=='TECHNICIAN'){<a mat-flat-button routerLink="/reports/new">＋ {{i.t('Nueva incidencia','New report')}}</a>}</div>
<section class="panel"><form class="filter-grid" (ngSubmit)="load()"><mat-form-field appearance="outline"><mat-label>{{i.t('Buscar incidencia','Search reports')}}</mat-label><input matInput name="q" [(ngModel)]="q" /></mat-form-field><mat-form-field appearance="outline"><mat-label>{{i.t('Estado','Status')}}</mat-label><mat-select name="status" [(ngModel)]="status"><mat-option value="">{{i.t('Todos','All')}}</mat-option>@for(s of statuses;track s){<mat-option [value]="s">{{i.label(s)}}</mat-option>}</mat-select></mat-form-field><mat-form-field appearance="outline"><mat-label>{{i.t('Categoría','Category')}}</mat-label><mat-select name="categoryId" [(ngModel)]="categoryId"><mat-option value="">{{i.t('Todas','All')}}</mat-option>@for(c of categories;track c.id){<mat-option [value]="c.id">{{c.name}}</mat-option>}</mat-select></mat-form-field><mat-form-field appearance="outline"><mat-label>{{i.t('Área','Area')}}</mat-label><mat-select name="areaId" [(ngModel)]="areaId"><mat-option value="">{{i.t('Todas','All')}}</mat-option>@for(a of areas;track a.id){<mat-option [value]="a.id">{{a.name}}</mat-option>}</mat-select></mat-form-field><mat-form-field appearance="outline"><mat-label>{{i.t('Prioridad','Priority')}}</mat-label><mat-select name="priority" [(ngModel)]="priority"><mat-option value="">{{i.t('Todas','All')}}</mat-option>@for(p of priorities;track p){<mat-option [value]="p">{{i.label(p)}}</mat-option>}</mat-select></mat-form-field><button mat-flat-button type="submit" [disabled]="loading">{{i.t('Filtrar','Filter')}}</button></form>
@if(loading){<mat-progress-bar mode="indeterminate" [attr.aria-label]="i.t('Cargando incidencias','Loading reports')"/>}@if(error){<p role="alert" class="alert error">{{error}}</p>}
@if(!loading && !error){<div class="section-heading"><h2>{{i.t('Reportes','Reports')}} <span class="count">{{reports.length}}</span></h2><span class="muted">{{i.t('Más recientes primero','Newest first')}}</span></div><div class="table-scroll"><table><caption class="sr-only">{{i.t('Listado de incidencias','Report list')}}</caption><thead><tr><th>{{i.t('Incidencia','Report')}}</th><th>{{i.t('Área / categoría','Area / category')}}</th><th>{{i.t('Prioridad','Priority')}}</th><th>{{i.t('Estado','Status')}}</th><th>{{i.t('Registro','Created')}}</th></tr></thead><tbody>@for(r of reports;track r.id){<tr><td><a class="report-link" [routerLink]="['/reports',r.id]">{{r.title}}</a><small>#{{r.id}} · {{r.reporterName}}</small></td><td>{{r.areaName}}<small>{{r.categoryName}}</small></td><td><span class="priority" [class.urgent]="r.priority==='HIGH'||r.priority==='CRITICAL'">● {{i.label(r.priority)}}</span></td><td><span class="status" [attr.data-status]="r.status">{{i.label(r.status)}}</span></td><td class="date-cell">{{i.date(r.createdAt)}}</td></tr>}</tbody></table></div>@if(!reports.length){<div class="empty-state"><span aria-hidden="true">▤</span><h3>{{i.t('No encontramos incidencias','No reports found')}}</h3><p>{{i.t('Prueba otros filtros o registra una nueva incidencia.','Try other filters or create a new report.')}}</p></div>}}</section>`})
export class ReportsComponent implements OnInit {api=inject(Api);i=inject(I18n);reports:Report[]=[];categories:Catalog[]=[];areas:Catalog[]=[];q='';status='';categoryId:number|string='';areaId:number|string='';priority='';loading=false;error='';statuses=['NEW','ASSIGNED','IN_PROGRESS','RESOLVED','CLOSED'];priorities=['LOW','MEDIUM','HIGH','CRITICAL'];async ngOnInit(){try{[this.categories,this.areas]=await Promise.all([this.api.get<Catalog[]>('/categories'),this.api.get<Catalog[]>('/areas')]);}catch(e){this.error=this.api.error(e);return;}await this.load();}async load(){this.loading=true;this.error='';const query=new URLSearchParams();Object.entries({q:this.q,status:this.status,categoryId:this.categoryId,areaId:this.areaId,priority:this.priority}).forEach(([key,value])=>{if(value)query.set(key,String(value));});try{this.reports=(await this.api.get<Report[]>('/reports?'+query)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));}catch(e){this.error=this.api.error(e);}finally{this.loading=false;}}}

