import { Component, inject, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { Api } from './api.service';
import { I18n } from './i18n.service';
import { Comment, Report, Status, Technician } from './models';
import { MATERIAL } from './material';
@Component({standalone:true,imports:[FormsModule,RouterLink,...MATERIAL],template:`
<a routerLink="/reports" class="back-link">← {{i.t('Volver a incidencias','Back to reports')}}</a>
@if(loading){<mat-progress-bar mode="indeterminate" [attr.aria-label]="i.t('Cargando incidencia','Loading report')"/>}@if(error){<p role="alert" class="alert error">{{error}}</p>}
@if(report;as r){<div class="page-heading"><div><span class="eyebrow">{{i.t('INCIDENCIA','REPORT')}} #{{r.id}}</span><h1>{{r.title}}</h1><p>{{i.t('Registrada por','Reported by')}} {{r.reporterName}} · {{i.date(r.createdAt)}}</p></div><span class="status" [attr.data-status]="r.status">{{i.label(r.status)}}</span></div>
<div class="form-layout"><div><section class="panel"><h2>{{i.t('Descripción','Description')}}</h2><p class="preserve-lines">{{r.description}}</p><dl class="detail-grid"><div><dt>{{i.t('Área','Area')}}</dt><dd>{{r.areaName}}</dd></div><div><dt>{{i.t('Ubicación','Location')}}</dt><dd>{{r.location}}</dd></div><div><dt>{{i.t('Categoría','Category')}}</dt><dd>{{r.categoryName}}</dd></div><div><dt>{{i.t('Prioridad','Priority')}}</dt><dd>{{i.label(r.priority)}}</dd></div><div><dt>{{i.t('Técnico asignado','Assigned technician')}}</dt><dd>{{r.technicianName || i.t('Por asignar','Unassigned')}}</dd></div></dl>
@if(canEdit()){<div class="form-actions"><a mat-stroked-button [routerLink]="['/reports',r.id,'edit']">{{i.t('Editar','Edit')}}</a><button mat-button class="danger" (click)="confirmDelete=true">{{i.t('Eliminar','Delete')}}</button></div>}
@if(confirmDelete){<div class="alert error"><p>{{i.t('¿Eliminar esta incidencia nueva? Esta acción no se puede deshacer.','Delete this new report? This action cannot be undone.')}}</p><button mat-button (click)="confirmDelete=false">{{i.t('Cancelar','Cancel')}}</button><button mat-flat-button (click)="remove()" [disabled]="busy">{{i.t('Confirmar eliminación','Confirm deletion')}}</button></div>}</section>
<section class="panel spaced"><h2>{{i.t('Historial de atención','Activity history')}}</h2><ol class="timeline">@for(h of r.history;track h.id){<li><span class="timeline-dot"></span><strong>{{i.label(h.toStatus)}}</strong><small>{{h.actorName}} · {{i.date(h.createdAt)}}</small><p>{{h.note}}</p></li>}@empty{<li>{{i.t('Aún no hay movimientos.','No activity yet.')}}</li>}</ol></section>
<section class="panel spaced"><h2>{{i.t('Comentarios','Comments')}}</h2><div class="comment-list">@for(c of comments;track c.id){<article class="comment"><strong>{{c.authorName}}</strong><small>{{i.date(c.createdAt)}}</small><p class="preserve-lines">{{c.body}}</p></article>}@empty{<p class="muted">{{i.t('Todavía no hay comentarios.','No comments yet.')}}</p>}</div><form #commentForm="ngForm" (ngSubmit)="addComment()"><mat-form-field appearance="outline"><mat-label>{{i.t('Escribe un comentario','Write a comment')}}</mat-label><textarea matInput name="commentBody" [(ngModel)]="commentBody" required maxlength="2000" rows="3"></textarea></mat-form-field><button mat-flat-button [disabled]="commentForm.invalid||busy">{{i.t('Agregar comentario','Add comment')}}</button></form></section>
<section class="panel spaced"><h2>{{i.t('Notificaciones por correo','Email notifications')}}</h2><p class="muted">{{i.t('El estado refleja el resultado real registrado por el servidor.','Status reflects the actual result recorded by the server.')}}</p>@for(n of r.notifications;track n.id){<div class="notification"><strong>{{n.status}}</strong><span>{{n.recipient}}</span><small>{{i.date(n.createdAt)}} · {{n.detail}}</small></div>}@empty{<p>{{i.t('No hay notificaciones registradas.','No notifications recorded.')}}</p>}</section></div>
<aside><section class="panel"><h2>{{i.t('Siguiente paso','Next step')}}</h2>
@if(canAssign()){<form #assignment="ngForm" (ngSubmit)="assign()"><mat-form-field appearance="outline"><mat-label>{{i.t('Técnico responsable','Responsible technician')}}</mat-label><mat-select name="technicianId" [(ngModel)]="technicianId" required>@for(t of technicians;track t.id){<mat-option [value]="t.id">{{t.name}} · {{t.specialty}}</mat-option>}</mat-select></mat-form-field><mat-form-field appearance="outline"><mat-label>{{i.t('Nota de asignación','Assignment note')}}</mat-label><textarea matInput name="assignmentNote" [(ngModel)]="assignmentNote" maxlength="2000"></textarea></mat-form-field><button mat-flat-button [disabled]="assignment.invalid||busy">{{i.t('Asignar técnico','Assign technician')}}</button></form>}
@if(nextStatus();as next){<form #transitionForm="ngForm" (ngSubmit)="transition(next)"><h3>{{i.label(next)}}</h3><mat-form-field appearance="outline"><mat-label>{{i.t('Nota de atención','Service note')}}</mat-label><textarea matInput name="note" [(ngModel)]="note" [required]="next==='RESOLVED'" maxlength="2000" rows="3"></textarea><mat-error>{{i.t('Describe cómo se resolvió.','Describe how the issue was resolved.')}}</mat-error></mat-form-field><button mat-flat-button [disabled]="transitionForm.invalid||busy">{{i.t('Marcar como','Mark as')}} {{i.label(next)}}</button></form>}
@if(!canAssign()&&!nextStatus()){<p>{{i.t('No tienes acciones pendientes en este estado. Sigue el avance desde el historial.','You have no pending actions in this state. Follow progress in the history.')}}</p>}</section></aside></div>}`})
export class ReportDetailComponent implements OnInit {
  api=inject(Api);i=inject(I18n);route=inject(ActivatedRoute);router=inject(Router);id=Number(this.route.snapshot.paramMap.get('id'));report:Report|null=null;comments:Comment[]=[];commentBody='';technicians:Technician[]=[];technicianId:number|null=null;assignmentNote='';note='';loading=false;busy=false;error='';confirmDelete=false;
  ngOnInit(){void this.load();}
  async load(){this.loading=true;this.error='';try{this.report=await this.api.get<Report>('/reports/'+this.id);this.comments=await this.api.get<Comment[]>('/reports/'+this.id+'/comments');if(this.api.user()?.role==='ADMIN')this.technicians=(await this.api.get<Technician[]>('/technicians')).filter(t=>t.active);}catch(e){this.error=this.api.error(e);}finally{this.loading=false;}}
  canEdit(){const u=this.api.user(),r=this.report;return r?.status==='NEW'&&(u?.role==='ADMIN'||u?.id===r?.reporterId);}
  canAssign(){return this.api.user()?.role==='ADMIN'&&!!this.report&&['NEW','ASSIGNED','IN_PROGRESS'].includes(this.report.status);}
  nextStatus():Status|null{const u=this.api.user(),r=this.report;if(!u||!r)return null;const operator=u.role==='ADMIN'||u.role==='TECHNICIAN';if(operator&&r.status==='ASSIGNED')return 'IN_PROGRESS';if(operator&&r.status==='IN_PROGRESS')return 'RESOLVED';if(r.status==='RESOLVED'&&(u.role==='ADMIN'||u.id===r.reporterId))return 'CLOSED';return null;}
  async assign(){await this.action('/assign',{technicianId:this.technicianId,note:this.assignmentNote});}
  async transition(status:Status){await this.action('/transition',{status,note:this.note});}
  async addComment(){this.busy=true;this.error='';try{const c=await this.api.write<Comment>('POST','/reports/'+this.id+'/comments',{body:this.commentBody});this.comments=[...this.comments,c];this.commentBody='';}catch(e){this.error=this.api.error(e);}finally{this.busy=false;}}
  async action(path:string,body:unknown){this.busy=true;this.error='';try{this.report=await this.api.write<Report>('POST','/reports/'+this.id+path,body);this.note='';this.assignmentNote='';}catch(e){this.error=this.api.error(e);}finally{this.busy=false;}}
  async remove(){this.busy=true;try{await this.api.write('DELETE','/reports/'+this.id);await this.router.navigate(['/reports']);}catch(e){this.error=this.api.error(e);}finally{this.busy=false;}}
}
